# Generated by Django 5.0.2 on 2025-08-16 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CahierCharges',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_projet', models.CharField(choices=[('site_web', 'Site Web'), ('app_mobile', 'Application Mobile'), ('ia', 'Intelligence Artificielle'), ('mariage', 'Cahier de charges Mariage'), ('construction', 'Chantier de Construction')], max_length=20)),
                ('nom_projet', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('fonctionnalites', models.TextField(blank=True)),
                ('technologies', models.TextField(blank=True)),
                ('budget', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('delai', models.CharField(blank=True, max_length=100)),
                ('public_cible', models.TextField(blank=True)),
                ('contraintes_techniques', models.TextField(blank=True)),
                ('type_ia', models.CharField(blank=True, max_length=200)),
                ('donnees_requises', models.TextField(blank=True)),
                ('performance_attendue', models.TextField(blank=True)),
                ('date_mariage', models.DateField(blank=True, null=True)),
                ('lieu_mariage', models.CharField(blank=True, max_length=200)),
                ('nombre_invites', models.IntegerField(blank=True, null=True)),
                ('style_mariage', models.CharField(blank=True, max_length=200)),
                ('services_requis', models.TextField(blank=True)),
                ('type_construction', models.CharField(blank=True, max_length=200)),
                ('surface', models.CharField(blank=True, max_length=100)),
                ('localisation', models.CharField(blank=True, max_length=200)),
                ('materiaux', models.TextField(blank=True)),
                ('normes', models.TextField(blank=True)),
            ],
        ),
    ]
