# Generated by Django 5.0.1 on 2025-09-09 19:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cahier_charges", "0002_utilisateur_cahiercharges_utilisateur"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="PlanAbonnement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nom",
                    models.CharField(
                        choices=[
                            ("gratuit", "Gratuit (Starter)"),
                            ("essentiel", "Essentiel (10$/mois)"),
                            ("pro", "Pro (20$/mois)"),
                            ("pro_annuel", "Pro Annuel (100$/an)"),
                        ],
                        max_length=50,
                        unique=True,
                    ),
                ),
                (
                    "prix_mensuel",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "prix_annuel",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "max_cahiers",
                    models.PositiveIntegerField(default=3, help_text="0 pour illimité"),
                ),
                ("pdf_illimite", models.BooleanField(default=False)),
                ("collaboration", models.BooleanField(default=False)),
                ("historique_versions", models.BooleanField(default=False)),
                ("modeles_premium", models.BooleanField(default=False)),
                ("support_prioritaire", models.BooleanField(default=False)),
                ("support_premium", models.BooleanField(default=False)),
            ],
            options={
                "verbose_name": "Plan d'abonnement",
                "verbose_name_plural": "Plans d'abonnement",
            },
        ),
        migrations.AlterField(
            model_name="cahiercharges",
            name="utilisateur",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.CreateModel(
            name="CahierUtilisation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("mois", models.DateField()),
                ("nb_cahiers_crees", models.PositiveIntegerField(default=0)),
                ("nb_pdf_generes", models.PositiveIntegerField(default=0)),
                (
                    "utilisateur",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "unique_together": {("utilisateur", "mois")},
            },
        ),
        migrations.CreateModel(
            name="Abonnement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date_debut", models.DateField(auto_now_add=True)),
                ("date_fin", models.DateField(blank=True, null=True)),
                (
                    "statut",
                    models.CharField(
                        choices=[
                            ("actif", "Actif"),
                            ("en_attente", "En attente de paiement"),
                            ("expire", "Expiré"),
                            ("annule", "Annulé"),
                        ],
                        default="actif",
                        max_length=20,
                    ),
                ),
                ("paiement_recurrent", models.BooleanField(default=False)),
                ("derniere_facture", models.DateField(blank=True, null=True)),
                ("prochaine_facture", models.DateField(blank=True, null=True)),
                (
                    "utilisateur",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="abonnement",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "plan",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="cahier_charges.planabonnement",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="UtilisateurProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("entreprise", models.CharField(blank=True, max_length=200, null=True)),
                ("telephone", models.CharField(blank=True, max_length=20, null=True)),
                ("adresse", models.TextField(blank=True, null=True)),
                ("code_postal", models.CharField(blank=True, max_length=10, null=True)),
                ("ville", models.CharField(blank=True, max_length=100, null=True)),
                ("pays", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.DeleteModel(
            name="Utilisateur",
        ),
    ]
