# Generated by Django 5.0.1 on 2025-09-13 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "cahier_charges",
            "0003_planabonnement_alter_cahiercharges_utilisateur_and_more",
        ),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="planabonnement",
            options={
                "ordering": ["ordre_affichage"],
                "verbose_name": "Plan d'abonnement",
                "verbose_name_plural": "Plans d'abonnement",
            },
        ),
        migrations.RemoveField(
            model_name="planabonnement",
            name="modeles_premium",
        ),
        migrations.RemoveField(
            model_name="planabonnement",
            name="pdf_illimite",
        ),
        migrations.AddField(
            model_name="planabonnement",
            name="description",
            field=models.TextField(
                blank=True, help_text="Description du plan pour l'affichage"
            ),
        ),
        migrations.AddField(
            model_name="planabonnement",
            name="modeles_avances",
            field=models.BooleanField(
                default=False,
                help_text="Accès aux modèles avancés",
                verbose_name="Modèles avancés",
            ),
        ),
        migrations.AddField(
            model_name="planabonnement",
            name="ordre_affichage",
            field=models.PositiveIntegerField(
                default=0,
                help_text="Ordre d'affichage dans la liste des plans (du plus petit au plus grand)",
            ),
        ),
        migrations.AddField(
            model_name="planabonnement",
            name="partage_pdf",
            field=models.BooleanField(
                default=False,
                help_text="Possibilité de partager les PDF",
                verbose_name="Partage PDF",
            ),
        ),
        migrations.AddField(
            model_name="planabonnement",
            name="support_basique",
            field=models.BooleanField(
                default=True,
                help_text="Support de base par email",
                verbose_name="Support basique",
            ),
        ),
        migrations.AddField(
            model_name="planabonnement",
            name="telechargement_pdf",
            field=models.PositiveIntegerField(
                default=1,
                help_text="Nombre de PDF téléchargeables (0 pour illimité, -1 pour prévisualisation uniquement)",
                verbose_name="Téléchargement PDF",
            ),
        ),
        migrations.AlterField(
            model_name="planabonnement",
            name="collaboration",
            field=models.BooleanField(
                default=False,
                help_text="Fonctionnalités de collaboration en équipe",
                verbose_name="Collaboration",
            ),
        ),
        migrations.AlterField(
            model_name="planabonnement",
            name="historique_versions",
            field=models.BooleanField(
                default=False,
                help_text="Historique des versions des cahiers",
                verbose_name="Historique versions",
            ),
        ),
        migrations.AlterField(
            model_name="planabonnement",
            name="max_cahiers",
            field=models.PositiveIntegerField(
                default=3,
                help_text="Nombre maximum de cahiers par mois (0 pour illimité)",
                verbose_name="Cahiers de charges / mois",
            ),
        ),
        migrations.AlterField(
            model_name="planabonnement",
            name="nom",
            field=models.CharField(
                choices=[
                    ("gratuit", "Starter (Gratuit)"),
                    ("essentiel", "Essentiel (10$/mois)"),
                    ("pro_mensuel", "Pro (20$/mois)"),
                    ("pro_annuel", "Pro (100$/an)"),
                ],
                max_length=50,
                unique=True,
            ),
        ),
        migrations.AlterField(
            model_name="planabonnement",
            name="prix_mensuel",
            field=models.DecimalField(
                blank=True, decimal_places=2, default=0, max_digits=10, null=True
            ),
        ),
        migrations.AlterField(
            model_name="planabonnement",
            name="support_premium",
            field=models.BooleanField(
                default=False,
                help_text="Support chat + email prioritaire",
                verbose_name="Support premium",
            ),
        ),
        migrations.AlterField(
            model_name="planabonnement",
            name="support_prioritaire",
            field=models.BooleanField(
                default=False,
                help_text="Support prioritaire par email",
                verbose_name="Support prioritaire",
            ),
        ),
    ]
