# Generated by Django 5.0.1 on 2025-09-14 12:13

from django.db import migrations

def create_initial_plans(apps, schema_editor):
    PlanAbonnement = apps.get_model('cahier_charges', 'PlanAbonnement')
    
    # Supprimer tous les plans existants pour éviter les doublons
    PlanAbonnement.objects.all().delete()
    
    # Plan Gratuit (Starter)
    PlanAbonnement.objects.create(
        nom='gratuit',
        description='Parfait pour tester le service avec des fonctionnalités de base',
        prix_mensuel=0,
        prix_annuel=0,
        max_cahiers=3,
        telechargement_pdf=1,  # 1 PDF téléchargeable
        partage_pdf=False,
        collaboration=False,
        historique_versions=False,
        modeles_avances=False,
        support_basique=True,
        support_prioritaire=False,
        support_premium=False,
        ordre_affichage=1
    )
    
    # Plan Essentiel (10€/mois)
    PlanAbonnement.objects.create(
        nom='essentiel',
        description='Idéal pour les freelances et PME avec des besoins réguliers',
        prix_mensuel=10,
        prix_annuel=100,  # 2 mois gratuits
        max_cahiers=10,
        telechargement_pdf=10,  # 10 PDF téléchargeables
        partage_pdf=True,
        collaboration=False,
        historique_versions=False,
        modeles_avances=False,
        support_basique=True,
        support_prioritaire=True,
        support_premium=False,
        ordre_affichage=2
    )
    
    # Plan Pro Mensuel (20€/mois)
    PlanAbonnement.objects.create(
        nom='pro_mensuel',
        description='Pour les professionnels ayant besoin de fonctionnalités avancées',
        prix_mensuel=20,
        prix_annuel=None,  # Pas de réduction pour le mensuel
        max_cahiers=0,  # Illimité
        telechargement_pdf=0,  # Illimité
        partage_pdf=True,
        collaboration=True,
        historique_versions=True,
        modeles_avances=True,
        support_basique=True,
        support_prioritaire=True,
        support_premium=False,
        ordre_affichage=3
    )
    
    # Plan Pro Annuel (100€/an)
    PlanAbonnement.objects.create(
        nom='pro_annuel',
        description='La solution la plus économique avec toutes les fonctionnalités',
        prix_mensuel=None,  # Seul le prix annuel s'applique
        prix_annuel=100,    # 58% d'économie par rapport au mensuel
        max_cahiers=0,      # Illimité
        telechargement_pdf=0,  # Illimité
        partage_pdf=True,
        collaboration=True,
        historique_versions=True,
        modeles_avances=True,
        support_basique=True,
        support_prioritaire=True,
        support_premium=True,  # Support premium inclus
        ordre_affichage=4
    )

class Migration(migrations.Migration):

    dependencies = [
        ('cahier_charges', '0004_alter_planabonnement_options_and_more'),
    ]

    operations = [
        migrations.RunPython(create_initial_plans, migrations.RunPython.noop),
    ]
