# Generated by Django 5.0.1 on 2025-09-20 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cahier_charges", "0006_transactioncinetpay"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="planabonnement",
            name="prix_annuel",
        ),
        migrations.RemoveField(
            model_name="planabonnement",
            name="prix_mensuel",
        ),
        migrations.AddField(
            model_name="planabonnement",
            name="prix_annuel_usd",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Prix annuel en USD (avec remise)",
                max_digits=10,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="planabonnement",
            name="prix_mensuel_usd",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                default=0,
                help_text="Prix mensuel en USD",
                max_digits=10,
                null=True,
            ),
        ),
    ]
