# Generated by manual migration

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("cahier_charges", "0007_remove_planabonnement_prix_annuel_and_more"),
    ]

    operations = [
        migrations.DeleteModel(
            name="TransactionCinetpay",
        ),
    ]
